# version: '3.8'

services:
  api:
    build: .
    image: ${IMAGE} 
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image:  mariadb #  mysql   
    # container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db_data:
